### ISSUE TITLE
Where is the rest

### ISSUE THREAD

**Issue by wallaica** [longwalter/RecRoom-Store-JSON#1]
Seems to be missing GUID's

**Comment by longwalter** [comment]
Do you happen to know where I could find the GUIDs for these items? They aren't accessible via the API due to the limitations of a recnet webClient JWT.

**Comment by wallaica** [comment]
I just made a gitlab with it please credit me tho
https://gitlab.com/minorcrimes/recnet-catalog-json/-/blob/main/outfitdata.json

**Comment by wallaica** [comment]
Basically add me on spookaica#0001

**Comment by wallaica** [comment]
Do you understand how GUID's work?

**Comment by wallaica** [comment]
Alright Thanks for the listening :wave: cya next time
